[tool.poetry]
name = "puzzle"
version = "0.1.0"
description = ""
authors = ["johnropp <johnwilliamropp@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
ipython = "^9.0.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
